version: '3'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - app-data:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

volumes:
  app-data:
